import type { Intent, Task } from '../types/index.ts';
import type { ProjectInfo } from './Analyzer.ts';

export class Roadmap {
  public static generate(intent: Intent, info: ProjectInfo): Task[] {
    const tasks: Task[] = [];
    let idCounter = 1;
    const lower = intent.original.toLowerCase();

    // 1. Requirement Analysis (Always needed)
    tasks.push({
        id: `T${idCounter++}`,
        description: 'Analyze requirements & Design data structure',
        status: 'TODO',
        type: 'MANUAL'
    });

    // 2. Framework Specific Logic - Now Multi-Compatible
    
    if (info.frameworks.includes('LARAVEL')) {
        if (lower.includes('user') || lower.includes('auth') || lower.includes('register')) {
            tasks.push({
                id: `T${idCounter++}`,
                description: 'Create Migration',
                status: 'TODO',
                type: 'SHELL',
                file: 'database/migrations/',
                command: 'php artisan make:migration create_users_table'
            });
            tasks.push({
                id: `T${idCounter++}`,
                description: 'Update Model',
                status: 'TODO',
                type: 'MANUAL',
                file: 'app/Models/User.php'
            });
        }
        if (lower.includes('api') || lower.includes('endpoint')) {
             tasks.push({
                id: `T${idCounter++}`,
                description: 'Create API Controller',
                status: 'TODO',
                type: 'SHELL',
                command: 'php artisan make:controller Api/V1/ResourceController --api'
             });
        }
    } 
    
    if (info.frameworks.includes('REACT') || info.frameworks.includes('NEXT') || info.frameworks.includes('VUE')) {
         const framework = info.frameworks.includes('NEXT') ? 'NEXT' : (info.frameworks.includes('VUE') ? 'VUE' : 'REACT');
         
         if (lower.includes('page') || lower.includes('screen') || lower.includes('view') || lower.includes('index')) {
             const pageName = lower.includes('index') || lower.includes('home') ? 'Home' : 'NewPage';
             const fileName = framework === 'NEXT' ? `src/app/${pageName.toLowerCase()}/page.tsx` : `src/pages/${pageName}.tsx`;
             
             tasks.push({
                id: `T${idCounter++}`,
                description: `Create ${framework} Page (${pageName})`,
                status: 'TODO',
                type: 'CREATE_FILE',
                file: fileName,
                content: `import React from 'react';

export default function ${pageName}() {
  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4">${pageName} Generated by Intent</h1>
      <p>This page was scaffolded automatically.</p>
    </div>
  );
}`
             });
         }
         
         const wantsComponent = lower.includes('component') || lower.includes('button') || lower.includes('form') || lower.includes('container') || lower.includes('navbar') || lower.includes('header') || lower.includes('sidebar'); 
         if (wantsComponent) {
             const compName = 'GeneratedComponent';
             tasks.push({
                id: `T${idCounter++}`,
                description: 'Create UI Component',
                status: 'TODO',
                type: 'CREATE_FILE',
                file: `src/components/${compName}.tsx`,
                content: `import React from 'react';

type Props = {
  title?: string;
  children?: React.ReactNode;
};

export const ${compName}: React.FC<Props> = ({ title = 'Component', children }) => {
  return (
    <div className="p-4 border rounded shadow-sm">
      <h2 className="font-bold text-lg">{title}</h2>
      <div>{children}</div>
    </div>
  );
};
`
             });
         }
         
         if (lower.includes('state') || lower.includes('store') || lower.includes('redux')) {
             tasks.push({
                id: `T${idCounter++}`,
                description: 'Setup State Management',
                status: 'TODO',
                type: 'CREATE_FILE',
                file: 'src/store/index.ts',
                content: `// State management store placeholder
export const store = {
  state: {},
  dispatch: (action: any) => console.log('Dispatch', action)
};`
             });
         }
    } 
    
    if (info.frameworks.includes('NEST')) {
        tasks.push({
            id: `T${idCounter++}`,
            description: 'Generate Module',
            status: 'TODO',
            type: 'SHELL',
            command: 'nest g module resource'
        });
    }

    if (info.frameworks.includes('PYTHON') || info.frameworks.includes('DJANGO')) {
         tasks.push({
            id: `T${idCounter++}`,
            description: 'Start App',
            status: 'TODO',
            type: 'SHELL',
            command: 'python manage.py startapp feature'
         });
    }

    // Default Fallback
    if (tasks.length === 1) {
        tasks.push({
            id: `T${idCounter++}`,
            description: 'Scaffold Implementation Files',
            status: 'TODO',
            type: 'MANUAL',
            file: 'src/'
        });
    }

    return tasks;
  }
}
